---
k3s_version: "v1.31.5+k3s1"
argocd_version: "v2.13.3"
argocd_install_sha256: "0940f3f92ee6b91141cefc5368b1379aed0aef898186879ea2ca5f2607ee2617"
argocd_namespace: argocd
argocd_root_app_name: final-platform
argocd_root_app_path: bootstrap/apps
argocd_repo_revision: main
cluster_cidr: 10.42.0.0/16
service_cidr: 10.43.0.0/16
gitops_repo_url: "{{ lookup('env', 'GITOPS_URL') }}"
gitops_username: "{{ lookup('env', 'GITOPS_USERNAME') | default('oauth2', true) }}"
gitops_token: "{{ lookup('env', 'GITOPS_TOKEN') }}"
app_host: "{{ lookup('env', 'APP_HOST') }}"
kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') }}"
